enum Combine { SUM, LATEST, AVERAGE, HIGH, LOW, UNKNOWN }

class DataTypes {
  static const List<String> WekoDataPointsBase = [
    'activeEnergyBurned',
    'basalEnergyBurned',
    'bloodGlucose',
    'bloodOxygen',
    'bloodPressureDiastolic',
    'bloodPressureSystolic',
    'bodyFatPercentage',
    'bodyMassIndex',
    'bodyTemperature',
    'electrodermalActivity',
    'heartRate',
    'height',
    'restingHeartRate',
    'steps',
    'waistCircumference',
    'walkingHeartRate',
    'weight',
    'distanceWalkingRunning',
    'flightsClimbed',
    'moveMinutes',
    'distanceDelta',
    'mindfulness',
    'sleepInBed',
    'sleepAsleep',
    'sleepAwake',
    'water',
    'highHeartRateEvent',
    'lowHeartRateEvent',
    'irregularHeartRateEvent',
    'heartRateVariabilitySDNN',
    'swimDistance',
    'bikeDistane'
  ];

  static const List<String> WekoApiPoints = [
    "activeEnergyBurned",
    "basalEnergyBurned",
    "steps",
    "distanceWalkingRunning",
    "flightsClimbed",
    "moveMinutes",
    "distanceDelta",
    "mindfulness",
    "sleepInBed",
    "sleepAsleep",
    "sleepAwake",
    "water",
    "highHeartRateEvent",
    "lowHeartRateEvent",
    "irregularHeartRateEvent",
    "swimDistance",
    "bikeDistance",
    "bloodGlucoseLatest",
    "bloodGlucoseAvg",
    "bloodOxygenLatest",
    "bloodOxygenAvg",
    "bloodPressureDiastolicLatest",
    "bloodPressureSystolicLatest",
    "bloodPressureDiastolicAvg",
    "bloodPressureSystolicAvg",
    "bodyMassIndexLastest",
    "bodyFatPercentageLatest",
    "bodyTemperatureLatest",
    "bodyTemperatureAvg",
    "electrodermalActivityAvg",
    "heartRateAvg",
    "heightLatest",
    "restingHeartRateAvg",
    "waistCircumferenceLatest",
    "walkingHeartRateAvg",
    "weightLatest",
    "heartRateVariabilitySDNNAvg",
    "heartRateVariabilitySDNNHigh",
    "heartRateVariabilitySDNNLow"
  ];

  static const Map<String, List<Combine>> combinationMap = {
    'activeEnergyBurned': [Combine.SUM],
    'basalEnergyBurned': [Combine.SUM],
    'bloodGlucose': [Combine.LATEST, Combine.AVERAGE],
    'bloodOxygen': [Combine.LATEST, Combine.AVERAGE],
    'bloodPressureDiastolic': [Combine.LATEST, Combine.AVERAGE],
    'bloodPressureSystolic': [Combine.LATEST, Combine.AVERAGE],
    'bodyFatPercentage': [Combine.LATEST],
    'bodyMassIndex': [Combine.LATEST],
    'bodyTemperature': [Combine.LATEST, Combine.AVERAGE],
    'electrodermalActivity': [Combine.AVERAGE],
    'heartRate': [Combine.AVERAGE],
    'height': [Combine.LATEST],
    'restingHeartRate': [Combine.AVERAGE],
    'steps': [Combine.SUM],
    'waistCircumference': [Combine.LATEST],
    'walkingHeartRate': [Combine.AVERAGE],
    'weight': [Combine.LATEST],
    'distanceWalkingRunning': [Combine.SUM],
    'flightsClimbed': [Combine.SUM],
    'moveMinutes': [Combine.SUM],
    'distanceDelta': [Combine.SUM],
    'mindfulness': [Combine.SUM],
    'sleepInBed': [Combine.SUM],
    'sleepAsleep': [Combine.SUM],
    'sleepAwake': [Combine.SUM],
    'water': [Combine.SUM],
    'highHeartRateEvent': [Combine.UNKNOWN],
    'lowHeartRateEvent': [Combine.UNKNOWN],
    'irregularHeartRateEvent': [Combine.UNKNOWN],
    'heartRateVariabilitySDNN': [Combine.AVERAGE, Combine.HIGH, Combine.LOW],
    'swimDistance': [Combine.SUM],
    'bikeDistance': [Combine.SUM],
  };
}
